services:
  zookeeper:
    image: zookeeper:3.7
    platform: linux/amd64
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      - ZOO_CLIENT_PORT=2181
      - ZOO_TICK_TIME=2000
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - zookeeper
  
  secondarynamenode:
    build: ./secondarynamenode
    platform: linux/amd64
    container_name: secondarynamenode
    restart: always
    ports:
      - 9868:9868
    volumes:
      - hadoop_secondarynamenode:/hadoop/dfs/namesecondary
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - zookeeper
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    # container_name: datanode
    restart: always
    # ports:
    #   - 9864:9864
    volumes:
      - /hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - zookeeper

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: resourcemanager
    restart: always
    ports:
      - 8088:8088
    environment:
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - zookeeper

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: nodemanager
    restart: always
    ports:
      - 8042:8042
    environment:
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864,resourcemanager:8088
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - resourcemanager
      - namenode
      - datanode
      - zookeeper

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    platform: linux/amd64
    container_name: historyserver
    restart: always
    ports:
      - 8188:8188
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      - SERVICE_PRECONDITION=namenode:9000,namenode:9870,datanode:9864,resourcemanager:8088
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - datanode
      - resourcemanager
      - zookeeper

  hue:
    image: gethue/hue:4.8.0
    platform: linux/amd64
    container_name: hue
    restart: always
    ports:
      - 8888:8888
    environment:
      - HUE_DATABASE_ENGINE=sqlite3
      - HUE_DATABASE_NAME=/hue/desktop/desktop.db
      - HUE_DATABASE_USER=hue
      - HUE_DATABASE_PASSWORD=hue
      - POLARS_SKIP_CPU_CHECK=1
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper:2181
    env_file:
      - ./hadoop.env
    depends_on:
      - namenode
      - resourcemanager
      - zookeeper

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  zookeeper_data:
  zookeeper_datalog:
  hadoop_secondarynamenode:
